### ISSUE TITLE
Add MaxEE to help evaluate quality

### ISSUE THREAD

**Issue by amoliverio** [amoliverio/dada2_fiererlab#2]
https://github.com/RemiMaglione/r-scripts/blob/master/Qual_vs_MaxEE_plot.R

**Comment by hhollandmoritz** [comment]
Probably better to implement the quality graphs from the non-big data pipeline here instead, since Fastqc is likely to take a long time to run.

**Comment by hhollandmoritz** [comment]
Solved by adding plots of quality scores.
