### ISSUE TITLE
add more stringent filtering

### ISSUE THREAD

**Issue by amoliverio** [amoliverio/dada2_fiererlab#29]
# current filter
input_filt <- filter_taxa_from_input(input_filt, at_spec_level = 1, taxa_to_remove = "NA")

# to add 
input_filt <- filter_taxa_from_input(input_filt, at_spec_level = 2, taxa_to_remove = "NA")

looks like some taxa that are questionable make it through when only filter at domain level (e.g. assigned to bacteria) - i think adding one more step would improve this. likely because we don't have the match to public database step anymore

**Comment by hhollandmoritz** [comment]
Fixed in latest version.
